import { compileMDX }  from 'next-mdx-remote/rsc';
import { getSiteConfig } from '@/lib/site-config';
import { getMdxPage }   from '@/lib/mdx';
import Hero           from '@/components/home/Hero';
import Stats          from '@/components/home/Stats';
import ServicesGrid   from '@/components/home/ServicesGrid';
import WhyChooseUs    from '@/components/home/WhyChooseUs';
import Process        from '@/components/home/Process';
import Gallery        from '@/components/home/Gallery';
import Testimonials   from '@/components/home/Testimonials';
import ServiceAreas   from '@/components/home/ServiceAreas';
import EmergencyCTA   from '@/components/home/EmergencyCTA';
import SchemaScript   from '@/components/shared/SchemaScript';
import FAQ            from '@/components/service/FAQ';
import ServiceSectionBand from '@/components/service/ServiceSectionBand';
import PageIntro      from '@/components/service/PageIntro';

export async function generateMetadata() {
  const config = getSiteConfig();
  const page   = getMdxPage('services', 'homepage');
  const fm     = page?.frontmatter ?? {};
  return {
    title:       fm.meta_title       ?? `${config.business_name} | ${config.wp_title_tagline ?? config.tagline ?? ''}`,
    description: fm.meta_description ?? config.meta_description_default ?? `${config.business_name} serves ${config.city}, ${config.state} and surrounding areas.`,
  };
}

export default async function HomePage() {
  const config = getSiteConfig();

  // Hero image — pulled from config or left null for gradient fallback
  const heroImage = config.hero_image ?? null;

  // Homepage MDX content — generated by content engine, lives at content/services/homepage.mdx
  const homePage    = getMdxPage('services', 'homepage');
  const fm          = homePage?.frontmatter ?? {};
  const faqItems    = fm.faq ?? [];
  const images      = fm.images ?? [];
  const imgBySlot   = (slot) => images.find(i => i.slot === slot) ?? null;
  const sectionState = { index: 0 };

  const components = {
    PageIntro: ({ children }) => <PageIntro>{children}</PageIntro>,
    ServiceSection: ({ slot, heading, children }) => {
      const idx   = sectionState.index++;
      const image = imgBySlot(slot);
      return (
        <ServiceSectionBand slot={slot} heading={heading} index={idx} image={image}>
          {children}
        </ServiceSectionBand>
      );
    },
    FAQSection: () => <FAQ items={faqItems} />,
  };

  let mdxContent = null;
  if (homePage?.content) {
    const result = await compileMDX({
      source:     homePage.content,
      options:    { parseFrontmatter: false },
      components,
    });
    mdxContent = result.content;
  }

  return (
    <>
      <SchemaScript schema={fm.schema} />

      {/* 1. Hero — full bleed, H1, dual CTA */}
      <Hero config={config} heroImage={heroImage} />


      {/* 3. Stats row — years / jobs / rating / response time */}
      <Stats config={config} />

      {/* 4. Services grid — 3-col cards */}
      <ServicesGrid config={config} />

      {/* 5. Homepage MDX — PageIntro + ServiceSection bands + FAQSection */}
      {mdxContent}

      {/* 6. Why choose us — differentiator cards */}
      <WhyChooseUs config={config} />

      {/* 7. Process — numbered steps */}
      <Process config={config} />

      {/* 8. Project gallery */}
      <Gallery config={config} />

      {/* 9. Testimonials */}
      <Testimonials config={config} />

      {/* 10. Service areas geographic strip */}
      <ServiceAreas config={config} />

      {/* 11. Emergency CTA band */}
      <EmergencyCTA config={config} />
    </>
  );
}
