import { compileMDX }  from 'next-mdx-remote/rsc';
import { getSiteConfig } from '@/lib/site-config';
import { getMdxPage }   from '@/lib/mdx';
import Hero           from '@/components/home/Hero';
import SocialProof    from '@/components/home/SocialProof';
import Stats          from '@/components/home/Stats';
import ServicesGrid   from '@/components/home/ServicesGrid';
import WhyChooseUs    from '@/components/home/WhyChooseUs';
import Process        from '@/components/home/Process';
import Gallery        from '@/components/home/Gallery';
import Testimonials   from '@/components/home/Testimonials';
import ServiceAreas   from '@/components/home/ServiceAreas';
import EmergencyCTA   from '@/components/home/EmergencyCTA';
import SchemaScript   from '@/components/shared/SchemaScript';
import MdxStyles      from '@/components/shared/MdxStyles';
import FAQ            from '@/components/service/FAQ';

export async function generateMetadata() {
  const config = getSiteConfig();
  const page   = getMdxPage('services', 'homepage');
  const fm     = page?.frontmatter ?? {};
  return {
    title:       fm.meta_title       ?? `${config.business_name} | ${config.wp_title_tagline ?? config.tagline ?? ''}`,
    description: fm.meta_description ?? config.meta_description_default ?? `${config.business_name} serves ${config.city}, ${config.state} and surrounding areas.`,
  };
}

export default async function HomePage() {
  const config = getSiteConfig();

  // Hero image — pulled from config or left null for gradient fallback
  const heroImage = config.hero_image ?? null;

  // Homepage MDX content — generated by content engine, lives at content/services/homepage.mdx
  const homePage    = getMdxPage('services', 'homepage');
  const fm          = homePage?.frontmatter ?? {};
  const faqItems    = fm.faq ?? [];

  let mdxContent = null;
  if (homePage?.content) {
    const result = await compileMDX({
      source:  homePage.content,
      options: { parseFrontmatter: false },
    });
    mdxContent = result.content;
  }

  return (
    <>
      <SchemaScript schema={fm.schema} />

      {/* 1. Hero — full bleed, H1, dual CTA */}
      <Hero config={config} heroImage={heroImage} />

      {/* 2. Social proof strip — review count + stars */}
      <SocialProof config={config} />

      {/* 3. Stats row — years / jobs / rating / response time */}
      <Stats config={config} />

      {/* 4. Services grid — 3-col cards */}
      <ServicesGrid config={config} />

      {/* 5. Homepage MDX prose — SEO content, service category intros, local signals */}
      {mdxContent && (
        <section className="section-pad bg-surface">
          <div className="container">
            <article
              className="mdx-content"
              style={{
                fontSize:   '1.0625rem',
                lineHeight: 1.75,
                color:      'var(--color-text-body)',
                maxWidth:   860,
                margin:     '0 auto',
              }}
            >
              {mdxContent}
            </article>
          </div>
        </section>
      )}

      {/* 6. FAQ — from homepage MDX frontmatter */}
      {faqItems.length > 0 && <FAQ items={faqItems} />}

      {/* 7. Why choose us — differentiator cards */}
      <WhyChooseUs config={config} />

      {/* 8. Process — numbered steps */}
      <Process config={config} />

      {/* 9. Project gallery */}
      <Gallery config={config} />

      {/* 10. Testimonials */}
      <Testimonials config={config} />

      {/* 11. Service areas geographic strip */}
      <ServiceAreas config={config} />

      {/* 12. Emergency CTA band */}
      <EmergencyCTA config={config} />

      <MdxStyles />
    </>
  );
}
